version: '3.8'
services:
  usuarios:
    build:
      context: ./usuariosflask
    ports:
      - "8080:8080"
    depends_on:
      - sqlite
      - mysql

  contenidos:
    build:
      context: ./contenidosflask
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  visualizaciones_recomendaciones:
    build:
      context: ./visualizaciones_recomendacionesflask
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - usuarios
      - contenidos
      - visualizaciones_recomendaciones

  mongodb:
    image: docker.io/mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db:Z # SELinux labeling

  sqlite:
    image: docker.io/nouchka/sqlite3
    volumes:
      - ./usuariosflask/instance:/data:Z

  mysql:
    image: docker.io/library/mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: "usuarios_db"
    volumes:
      - ./mysql_data:/var/lib/mysql:Z
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always
