openapi: 3.0.3
info:
  title: Netflux Grupo 3 - OpenAPI 3.0
  description: API de Netflux realizada por el grupo 3 de la asignatura ASEE. Microservicio de **Visualizaciones y Recomendaciones**.
  license:
    name: Copyleft
    url: https://url/a/la/licencia
  version: 0.0.1
servers:
    - url: https://path/api/v1
tags:
    - name: Visualizacion
      description: Datos sobre las visualizaciones
    - name: Recomendacion
      description: Datos sobre las recomendaciones

paths: 
  /visualizacion/{perfilId}:
    get: # Este tiene mala pinta 
      tags:
        - Visualizacion
      summary: Historial de un perfil en específico
      description: Obtiene una lista de todos los capítulos o películas visualizados o en progreso por el perfil especificado.
      operationId: listarVisualizacionesPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil a obtener
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Lista de visualizaciones obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Visualizacion'
        '404':
          description: Perfil no encontrado
        '500':
          description: Error interno del servidor
          
    post:
      tags:
        - Visualizacion
      summary: Inicia la visualización de un capítulo o película por un perfil
      description: Inicia la visualización de un capítulo o película por un perfil
      operationId: crearVisualizacionContenidoPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil especificado
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: ID del contenido a visualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Visualizacion'
      responses:
        '201':
          description: Visualización creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Visualizacion'
        '404':
          description: Perfil no encontrado
        '500':
          description: Error interno del servidor
  
  /visualizacion/{contenidoId}:
    get:
      tags:
        - Visualizacion
      summary: Lista de perfiles que han visto el contenido especificado
      description: Lista de perfiles que han visto el contenido especificado.
      operationId: listarVisualizacionesContenido
      parameters:
        - name: contenidoId
          in: path
          description: ID del perfil a obtener
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Lista de visualizaciones obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Perfil'
        '404':
          description: Perfil no encontrado
        '500':
          description: Error interno del servidor
          
  /visualizacion/{perfilId}/{peliculaId}:
    get:
      tags:
        - Visualizacion
      summary: Obtiene la película visualizada por el perfil especificado
      description: Obtiene la película en visualización por el perfil especificado.
      operationId: obtenerVisualizacionPeliculaPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil a obtener
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - name: peliculaId
          in: path
          description: ID del perfil a obtener
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Película obtenida correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pelicula'
        '404':
          description: Perfil o contenido no encontrado
        '500':
          description: Error interno del servidor
          
    patch:
      tags:
        - Visualizacion
      summary: Actualiza la visualización de la película por un perfil
      description: Actualiza el progreso de la visualización de la película por un perfil
      operationId: actualizarVisualizacionPeliculaPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil específicado
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - name: peliculaId
          in: path
          description: ID de la película a actualizar
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '204':
          description: Visualización actualizada exitosamente
        '404':
          description: Perfil o película no encontrado
        '500':
          description: Error interno del servidor
          
  /visualizacion/{perfilId}/{capituloId}:
    get:
      tags:
        - Visualizacion
      summary: Obtiene el capítulo en visualización del perfil especificado
      description: Obtiene el capítulo en visualización por el perfil especificado.
      operationId: obtenerVisualizacionCapituloPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil a obtener
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - name: capituloId
          in: path
          description: ID del perfil a obtener
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Capítulo obtenido correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Capitulo'
        '404':
          description: Perfil o contenido no encontrado
        '500':
          description: Error interno del servidor
        
    patch:
      tags:
        - Visualizacion
      summary: Actualiza la visualización de un capítulo por un perfil
      description: Actualiza el progreso de la visualización de un capítulo por un perfil
      operationId: actualizarVisualizacionCapituloPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil especificado
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - name: capituloId
          in: path
          description: ID del capítulo especificado
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Película obtenida correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Capitulo'
        '404':
          description: Perfil o capítulo no encontrado
        '500':
          description: Error interno del servidor
          
  /perfil/{perfilId}/recomendaciones:
    get:
      tags:
        - Recomendacion
      summary: Obtiene una lista de las recomendaciones para el perfil
      description: Obtiene una lista de las recomendaciones para el perfil
      operationId: obtenerRecomendacionesPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil especificado
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Lista de recomendaciones obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recomendacion'
        '404':
          description: Perfil no encontrado
        '500':
          description: Error interno del servidor
          
    post:
      tags:
        - Recomendacion
      summary: Crea una recomendación para un perfil
      description: Crea una recomendación para un perfil en específico
      operationId: crearRecomendacionPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil especificado
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      requestBody:
        description: ID del contenido a visualizar
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Recomendacion'
      responses:
        '200':
          description: Recomendación creada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recomendacion'
        '404':
          description: Perfil o recomendacion no encontrado
        '500':
          description: Error interno del servidor
          
  /perfil/{perfilId}/recomendaciones/{recomendacionId}:
    get:
      tags:
        - Recomendacion
      summary: Obtiene una recomendación en específico de un perfil
      description: Obtiene una recomendación en específico de un perfil
      operationId: obtenerRecomendacionPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil especificado
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - name: recomendacionId
          in: path
          description: ID de la recomendacion especificada
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '200':
          description: Recomendación obtenida correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recomendacion'
        '404':
          description: Perfil o recomendacion no encontrado
        '500':
          description: Error interno del servidor
    
    delete:
      tags:
        - Recomendacion
      summary: Elimina una recomendación en específico de un perfil
      description: Elimina una recomendación en específico de un perfil
      operationId: eliminarRecomendacionPerfil
      parameters:
        - name: perfilId
          in: path
          description: ID del perfil especificado
          required: true
          schema:
            type: integer
            format: int64
            example: 1
        - name: recomendacionId
          in: path
          description: ID de la recomendacion especificada
          required: true
          schema:
            type: integer
            format: int64
            example: 1
      responses:
        '204':
          description: Recomendación eliminada correctamente
        '404':
          description: Perfil o recomendacion no encontrado
        '500':
          description: Error interno del servidor
      
components:
  schemas:
    Visualizacion:
      type: object
      properties:
        id_perfil:
          type: integer
          format: int64
          example: 1
        id_contenido:
          type: integer
          format: int64
          example: 1
        fecha_visualizacion:
          type: string
          format: date
          example: "2002-12-14"
        progreso:
          description: El porcentaje visualizado de un capítulo. Mínimo 0, máximo 100
          type: integer
          format: int32
          example: 20
           
    Recomendacion:
      type: object
      properties:
        id_recomendacion:
          type: integer
          format: int64
          example: 1
        id_perfil:
          type: integer
          format: int64
          example: 1
        contenido_recomendado:
          type: array
          items:
            $ref: '#/components/schemas/Capitulo'
            
    Perfil:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: ID del perfil en específico
          example: 1
        user_id:
          type: integer
          format: int64
          description: ID del usuario al que pertenece el perfil
          example: 3
        nombre:
          type: string
          example: "Euler"
        foto_perfil:
          type: string
          example: "path/to/image"
        historial_vistos:
          type: array
          items:
            $ref: '#/components/schemas/Capitulo'
        mi_lista:
          description: Lista con el contenido que el usuario ha guardado
          type: array
          items:
            $ref: '#/components/schemas/Capitulo'
        preferencias_contenido:
          type: object
          description: Preferencias de contenido del usuario
          properties: # Un par de ejemplos, tiene buena escalabilidad pero no nos volvamos locos
            genres:
              type: array
              items:
                type: string
              example:
                - "Action"
                - "Supernatural"
            languages:
              type: array
              items:
                type: string
                enum:
                  - Ingles
                  - Espanol
              example:
                - "Espanol"
      required:
        - nombre
            
    Serie:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        titulo:
          type: string
          example: "Breaking Bad"
        genero:
          type: string
          example: "Drama"
        sinopsis:
          type: string
          example: "Un profesor de química se convierte en fabricante de metanfetamina."
        anioEstreno:
          type: integer
          format: int32
          example: 2008
        temporadas:
          type: array
          items:
            $ref: '#/components/schemas/Temporada'
        actores:
          type: array
          items:
            $ref: '#/components/schemas/Actor'
      xml:
        name: serie
      required:
        - titulo
        - genero
        - sinopsis
        - anioEstreno

    Temporada:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        numero:
          type: integer
          format: int32
          example: 1
        anioLanzamiento:
          type: integer
          format: int32
          example: 2008
        capitulos:
          type: array
          items:
            $ref: '#/components/schemas/Capitulo'
      xml:
        name: temporada
      required:
        - numero
        - anioLanzamiento

    Capitulo:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        numero:
          type: integer
          format: int32
          example: 1
        titulo:
          type: string
          example: "Piloto"
        duracion:
          type: integer
          format: int32
          description: Duración del capítulo en minutos
          example: 58
        sinopsis:
          type: string
          example: "Walter White toma una decisión radical tras ser diagnosticado con cáncer de pulmón."
      xml:
        name: capitulo
      required:
        - numero
        - titulo
        - duracion
        
    Pelicula:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        titulo:
          type: string
          example: "Breaking Bad"
        genero:
          type: string
          example: "Drama"
        sinopsis:
          type: string
          example: "Un profesor de química se convierte en fabricante de metanfetamina."
        anioEstreno:
          type: integer
          format: int32
          example: 2008
        duracion:
          type: integer
          format: int32
          example: 112
        temporadas:
          type: array
          items:
            $ref: '#/components/schemas/Temporada'
        actores:
          type: array
          items:
            $ref: '#/components/schemas/Actor'
      xml:
        name: serie
      required:
        - titulo
        - genero
        - sinopsis
        - anioEstreno

    Actor:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nombre:
          type: string
          example: "Bryan Cranston"
        fechaNacimiento:
          type: string
          format: date
          example: "1956-03-07"
        personaje:
          type: string
          example: "Walter White"
        biografia:
          type: string
          example: "Actor estadounidense conocido por su papel en 'Breaking Bad'."
      xml:
        name: actor
      required:
        - nombre
        - personaje
