from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AsignarActorASerieRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, actor_id=None):  # noqa: E501
        """AsignarActorASerieRequest - a model defined in OpenAPI

        :param actor_id: The actor_id of this AsignarActorASerieRequest.  # noqa: E501
        :type actor_id: str
        """
        self.openapi_types = {
            'actor_id': str
        }

        self.attribute_map = {
            'actor_id': 'actor_id'
        }

        self._actor_id = actor_id

    @classmethod
    def from_dict(cls, dikt) -> 'AsignarActorASerieRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The asignarActorASerie_request of this AsignarActorASerieRequest.  # noqa: E501
        :rtype: AsignarActorASerieRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def actor_id(self) -> str:
        """Gets the actor_id of this AsignarActorASerieRequest.


        :return: The actor_id of this AsignarActorASerieRequest.
        :rtype: int
        """
        return self._actor_id

    @actor_id.setter
    def actor_id(self, actor_id: str):
        """Sets the actor_id of this AsignarActorASerieRequest.


        :param actor_id: The actor_id of this AsignarActorASerieRequest.
        :type actor_id: int
        """

        self._actor_id = actor_id
