from openapi_server import util
from openapi_server.models.base_model import Model

class AsignarActorRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, actor_id=None):  # noqa: E501
        """AsignarActorRequest - a model defined in OpenAPI

        :param actor_id: The actor_id of this AsignarActorRequest.  # noqa: E501
        :type actor_id: str
        """
        self.openapi_types = {
            'actor_id': str
        }

        self.attribute_map = {
            'actor_id': 'actor_id'
        }

        self._actor_id = actor_id

    @classmethod
    def from_dict(cls, dikt) -> 'AsignarActorRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The asignarActorASerie_request of this AsignarActorRequest.  # noqa: E501
        :rtype: AsignarActorRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def actor_id(self) -> str:
        """Gets the actor_id of this AsignarActorRequest.


        :return: The actor_id of this AsignarActorRequest.
        :rtype: int
        """
        return self._actor_id

    @actor_id.setter
    def actor_id(self, actor_id: str):
        """Sets the actor_id of this AsignarActorRequest.


        :param actor_id: The actor_id of this AsignarActorRequest.
        :type actor_id: int
        """

        self._actor_id = actor_id
