from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401
from bson import ObjectId

from openapi_server.models.base_model import Model
from openapi_server.models.actor import Actor
from openapi_server.models.serie import Serie, TemporadaEmbedded
# from openapi_server.models.temporada import Temporada
from openapi_server import util

class SerieUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, titulo=None, genero=None, sinopsis=None, anio_estreno=None, temporadas=None, actores=None):  # noqa: E501
        """SerieUpdate - a model defined in OpenAPI

        :param id: The id of this SerieUpdate.  # noqa: E501
        :type id: int
        :param titulo: The titulo of this SerieUpdate.  # noqa: E501
        :type titulo: str
        :param genero: The genero of this SerieUpdate.  # noqa: E501
        :type genero: str
        :param sinopsis: The sinopsis of this SerieUpdate.  # noqa: E501
        :type sinopsis: str
        :param anio_estreno: The anio_estreno of this SerieUpdate.  # noqa: E501
        :type anio_estreno: int
        :param temporadas: The temporadas of this SerieUpdate.  # noqa: E501
        :type temporadas: List[Temporada]
        :param actores: The actores of this SerieUpdate.  # noqa: E501
        :type actores: List[Actor]
        """
        self.openapi_types = {
            'id': int,
            'titulo': str,
            'genero': List[str],
            'sinopsis': str,
            'anio_estreno': int,
            'temporadas': List[TemporadaEmbedded],
            'actores': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'titulo': 'titulo',
            'genero': 'genero',
            'sinopsis': 'sinopsis',
            'anio_estreno': 'anio_estreno',
            'temporadas': 'temporadas',
            'actores': 'actores'
        }

        self._id = id
        self._titulo = titulo
        self._genero = genero
        self._sinopsis = sinopsis
        self._anio_estreno = anio_estreno
        self._temporadas = temporadas
        self._actores = actores

    def to_db_model(self):
        from openapi_server.models.serie_db import SerieDB
        return SerieDB(
            titulo=self._titulo,
            genero=self._genero,
            sinopsis=self._sinopsis,
            anio_estreno=self._anio_estreno,
            temporadas=[temporada.to_db_model() for temporada in self._temporadas] if self._temporadas else [],
            actores=[ObjectId(actor) for actor in self._actores] if self._actores else []
        )

    @classmethod
    def from_dict(cls, dikt) -> 'SerieUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SerieUpdate of this SerieUpdate.  # noqa: E501
        :rtype: SerieUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this SerieUpdate.


        :return: The id of this SerieUpdate.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this SerieUpdate.

        :param id: The id of this SerieUpdate.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def titulo(self) -> str:
        """Gets the titulo of this SerieUpdate.

        :return: The titulo of this SerieUpdate.
        :rtype: str
        """
        return self._titulo

    @titulo.setter
    def titulo(self, titulo: str):
        """Sets the titulo of this SerieUpdate.

        :param titulo: The titulo of this SerieUpdate.
        :type titulo: str
        """
        if titulo is None:
            raise ValueError("Invalid value for `titulo`, must not be `None`")  # noqa: E501

        self._titulo = titulo

    @property
    def genero(self) -> List[str]:
        """Gets the genero of this SerieUpdate.

        :return: The genero of this SerieUpdate.
        :rtype: str
        """
        return self._genero

    @genero.setter
    def genero(self, genero: List[str]):
        """Sets the genero of this SerieUpdate.


        :param genero: The genero of this SerieUpdate.
        :type genero: str
        """
        if genero is None:
            raise ValueError("Invalid value for `genero`, must not be `None`")  # noqa: E501

        self._genero = genero

    @property
    def sinopsis(self) -> str:
        """Gets the sinopsis of this SerieUpdate.


        :return: The sinopsis of this SerieUpdate.
        :rtype: str
        """
        return self._sinopsis

    @sinopsis.setter
    def sinopsis(self, sinopsis: str):
        """Sets the sinopsis of this SerieUpdate.


        :param sinopsis: The sinopsis of this SerieUpdate.
        :type sinopsis: str
        """
        if sinopsis is None:
            raise ValueError("Invalid value for `sinopsis`, must not be `None`")  # noqa: E501

        self._sinopsis = sinopsis

    @property
    def anio_estreno(self) -> int:
        """Gets the anio_estreno of this SerieUpdate.


        :return: The anio_estreno of this SerieUpdate.
        :rtype: int
        """
        return self._anio_estreno

    @anio_estreno.setter
    def anio_estreno(self, anio_estreno: int):
        """Sets the anio_estreno of this SerieUpdate.


        :param anio_estreno: The anio_estreno of this SerieUpdate.
        :type anio_estreno: int
        """
        if anio_estreno is None:
            raise ValueError("Invalid value for `anio_estreno`, must not be `None`")  # noqa: E501

        self._anio_estreno = anio_estreno

    @property
    def temporadas(self) -> List[TemporadaEmbedded]:
        """Gets the temporadas of this SerieUpdate.


        :return: The temporadas of this SerieUpdate.
        :rtype: List[Temporada]
        """
        return self._temporadas

    @temporadas.setter
    def temporadas(self, temporadas: List[TemporadaEmbedded]):
        """Sets the temporadas of this SerieUpdate.


        :param temporadas: The temporadas of this SerieUpdate.
        :type temporadas: List[Temporada]
        """

        self._temporadas = temporadas

    @property
    def actores(self) -> List[Actor]:
        """Gets the actores of this SerieUpdate.


        :return: The actores of this SerieUpdate.
        :rtype: List[Actor]
        """
        return self._actores

    @actores.setter
    def actores(self, actores: List[Actor]):
        """Sets the actores of this SerieUpdate.


        :param actores: The actores of this SerieUpdate.
        :type actores: List[Actor]
        """

        self._actores = actores
