from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.capitulo import Capitulo
from openapi_server import util

from openapi_server.models.capitulo import Capitulo  # noqa: E501

class Recomendacion(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id_recomendacion=None, id_perfil=None, contenido_recomendado=None):  # noqa: E501
        """Recomendacion - a model defined in OpenAPI

        :param id_recomendacion: The id_recomendacion of this Recomendacion.  # noqa: E501
        :type id_recomendacion: int
        :param id_perfil: The id_perfil of this Recomendacion.  # noqa: E501
        :type id_perfil: int
        :param contenido_recomendado: The contenido_recomendado of this Recomendacion.  # noqa: E501
        :type contenido_recomendado: List[Capitulo]
        """
        self.openapi_types = {
            'id_recomendacion': int,
            'id_perfil': int,
            'contenido_recomendado': List[Capitulo]
        }

        self.attribute_map = {
            'id_recomendacion': 'id_recomendacion',
            'id_perfil': 'id_perfil',
            'contenido_recomendado': 'contenido_recomendado'
        }

        self._id_recomendacion = id_recomendacion
        self._id_perfil = id_perfil
        self._contenido_recomendado = contenido_recomendado

    @classmethod
    def from_dict(cls, dikt) -> 'Recomendacion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Recomendacion of this Recomendacion.  # noqa: E501
        :rtype: Recomendacion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_recomendacion(self) -> int:
        """Gets the id_recomendacion of this Recomendacion.


        :return: The id_recomendacion of this Recomendacion.
        :rtype: int
        """
        return self._id_recomendacion

    @id_recomendacion.setter
    def id_recomendacion(self, id_recomendacion: int):
        """Sets the id_recomendacion of this Recomendacion.


        :param id_recomendacion: The id_recomendacion of this Recomendacion.
        :type id_recomendacion: int
        """

        self._id_recomendacion = id_recomendacion

    @property
    def id_perfil(self) -> int:
        """Gets the id_perfil of this Recomendacion.


        :return: The id_perfil of this Recomendacion.
        :rtype: int
        """
        return self._id_perfil

    @id_perfil.setter
    def id_perfil(self, id_perfil: int):
        """Sets the id_perfil of this Recomendacion.


        :param id_perfil: The id_perfil of this Recomendacion.
        :type id_perfil: int
        """

        self._id_perfil = id_perfil

    @property
    def contenido_recomendado(self) -> List[Capitulo]:
        """Gets the contenido_recomendado of this Recomendacion.


        :return: The contenido_recomendado of this Recomendacion.
        :rtype: List[Capitulo]
        """
        return self._contenido_recomendado

    @contenido_recomendado.setter
    def contenido_recomendado(self, contenido_recomendado: List[Capitulo]):
        """Sets the contenido_recomendado of this Recomendacion.


        :param contenido_recomendado: The contenido_recomendado of this Recomendacion.
        :type contenido_recomendado: List[Capitulo]
        """

        self._contenido_recomendado = contenido_recomendado
