from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.pelicula import Pelicula
from openapi_server import util

class RecomendacionPelicula(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id_recomendacion_pelicula=None, id_perfil=None, peliculas_recomendadas=None):  # noqa: E501
        """RecomendacionPelicula - a model defined in OpenAPI

        :param id_recomendacion_pelicula: The id_recomendacion of this RecomendacionPelicula.  # noqa: E501
        :type id_recomendacion_pelicula: int
        :param id_perfil: The id_perfil of this RecomendacionPelicula.  # noqa: E501
        :type id_perfil: int
        :param peliculas_recomendadas: The contenido_recomendado of this RecomendacionPelicula.  # noqa: E501
        :type peliculas_recomendadas: List[Pelicula]
        """
        self.openapi_types = {
            'id_recomendacion_pelicula': int,
            'id_perfil': int,
            'peliculas_recomendadas': List[Pelicula]
        }

        self.attribute_map = {
            'id_recomendacion_pelicula': 'id_recomendacion',
            'id_perfil': 'id_perfil',
            'peliculas_recomendadas': 'contenido_recomendado'
        }

        self._id_recomendacion_pelicula = id_recomendacion
        self._id_perfil = id_perfil
        self._peliculas_recomendadas = contenido_recomendado

    @classmethod
    def from_dict(cls, dikt) -> 'RecomendacionPelicula':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RecomendacionPelicula of this RecomendacionPelicula.  # noqa: E501
        :rtype: RecomendacionPelicula
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_recomendacion_pelicula(self) -> int:
        """Gets the id_recomendacion_pelicula of this RecomendacionPelicula.


        :return: The id_recomendacion_pelicula of this RecomendacionPelicula.
        :rtype: int
        """
        return self._id_recomendacion_pelicula

    @id_recomendacion_pelicula.setter
    def id_recomendacion_pelicula(self, id_recomendacion_pelicula: int):
        """Sets the id_recomendacion_pelicula of this RecomendacionPelicula.


        :param id_recomendacion_pelicula: The id_recomendacion of this RecomendacionPelicula.
        :type id_recomendacion_pelicula: int
        """

        self._id_recomendacion_pelicula = id_recomendacion_pelicula

    @property
    def id_perfil(self) -> int:
        """Gets the id_perfil of this RecomendacionPelicula.


        :return: The id_perfil of this RecomendacionPelicula.
        :rtype: int
        """
        return self._id_perfil

    @id_perfil.setter
    def id_perfil(self, id_perfil: int):
        """Sets the id_perfil of this RecomendacionPelicula.


        :param id_perfil: The id_perfil of this RecomendacionPelicula.
        :type id_perfil: int
        """

        self._id_perfil = id_perfil

    @property
    def peliculas_recomendadas(self) -> List[Pelicula]:
        """Gets the peliculas_recomendadas of this RecomendacionPelicula.


        :return: The peliculas_recomendadas of this RecomendacionPelicula.
        :rtype: List[Pelicula]
        """
        return self._peliculas_recomendadas

    @peliculas_recomendadas.setter
    def peliculas_recomendadas(self, peliculas_recomendadas: List[Pelicula]):
        """Sets the peliculas_recomendadas of this RecomendacionPelicula.


        :param peliculas_recomendadas: The contenido_recomendado of this RecomendacionPelicula.
        :type peliculas_recomendadas: List[Pelicula]
        """

        self._peliculas_recomendadas = peliculas_recomendadas
