from openapi_server import util
from openapi_server.models.base_model import Model

from datetime import date

class VisualizacionCapitulo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id_perfil=None, serie_id=None, temporada_id=None, capitulo_id=None, fecha_visualizacion=None):  # noqa: E501
        """VisualizacionCapitulo - a model defined in OpenAPI

        :param id_perfil: The id_perfil of this VisualizacionCapitulo.  # noqa: E501
        :type id_perfil: int
        :param capitulo_id: The capitulo_id of this VisualizacionCapitulo.  # noqa: E501
        :type capitulo_id: int
        :param fecha_visualizacion: The fecha_visualizacion of this VisualizacionCapitulo.  # noqa: E501
        :type fecha_visualizacion: date
        """
        self.openapi_types = {
            'id_perfil': int,
            'serie_id': str,
            'temporada_id': str,
            'capitulo_id': str,
            'fecha_visualizacion': date,
        }

        self.attribute_map = {
            'id_perfil': 'id_perfil',
            'serie_id': 'serie_id',
            'temporada_id': 'temporada_id',
            'capitulo_id': 'capitulo_id',
            'fecha_visualizacion': 'fecha_visualizacion',
        }

        self._id_perfil = id_perfil
        self._serie_id = serie_id
        self._temporada_id = temporada_id
        self._capitulo_id = capitulo_id
        self._fecha_visualizacion = fecha_visualizacion

    @classmethod
    def from_dict(cls, dikt) -> 'VisualizacionCapitulo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VisualizacionCapitulo of this Visualizacion.  # noqa: E501
        :rtype: VisualizacionCapitulo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_perfil(self) -> int:
        """Gets the id_perfil of this VisualizacionCapitulo.


        :return: The id_perfil of this VisualizacionCapitulo.
        :rtype: int
        """
        return self._id_perfil

    @id_perfil.setter
    def id_perfil(self, id_perfil: int):
        """Sets the id_perfil of this VisualizacionCapitulo.


        :param id_perfil: The id_perfil of this VisualizacionCapitulo.
        :type id_perfil: int
        """

        self._id_perfil = id_perfil

    @property
    def capitulo_id(self) -> str:
        """Gets the capitulo_id of this VisualizacionCapitulo.


        :return: The capitulo_id of this VisualizacionCapitulo.
        :rtype: int
        """
        return self._capitulo_id

    @capitulo_id.setter
    def capitulo_id(self, capitulo_id: str):
        """Sets the capitulo_id of this VisualizacionCapitulo.


        :param capitulo_id: The capitulo_id of this VisualizacionCapitulo.
        :type capitulo_id: int
        """

        self._capitulo_id = capitulo_id

    @property
    def serie_id(self) -> str:
        """Gets the serie_id of this VisualizacionCapitulo.


        :return: The serie_id of this VisualizacionCapitulo.
        :rtype: int
        """
        return self._serie_id

    @serie_id.setter
    def serie_id(self, serie_id: str):
        """Sets the serie_id of this VisualizacionCapitulo.


        :param serie_id: The serie_id of this VisualizacionCapitulo.
        :type serie_id: int
        """

        self._serie_id = serie_id

    @property
    def temporada_id(self) -> str:
        """Gets the temporada_id of this VisualizacionCapitulo.


        :return: The temporada_id of this VisualizacionCapitulo.
        :rtype: int
        """
        return self._temporada_id

    @temporada_id.setter
    def temporada_id(self, temporada_id: str):
        """Sets the temporada_id of this VisualizacionCapitulo.


        :param temporada_id: The temporada_id of this VisualizacionCapitulo.
        :type temporada_id: int
        """

        self._temporada_id = temporada_id

    @property
    def fecha_visualizacion(self) -> date:
        """Gets the fecha_visualizacion of this VisualizacionCapitulo.


        :return: The fecha_visualizacion of this VisualizacionCapitulo.
        :rtype: date
        """
        return self._fecha_visualizacion

    @fecha_visualizacion.setter
    def fecha_visualizacion(self, fecha_visualizacion: date):
        """Sets the fecha_visualizacion of this VisualizacionCapitulo.


        :param fecha_visualizacion: The fecha_visualizacion of this VisualizacionCapitulo.
        :type fecha_visualizacion: date
        """

        self._fecha_visualizacion = fecha_visualizacion
