from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Visualizacion(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id_perfil=None, id_contenido=None, fecha_visualizacion=None, progreso=None):  # noqa: E501
        """Visualizacion - a model defined in OpenAPI

        :param id_perfil: The id_perfil of this Visualizacion.  # noqa: E501
        :type id_perfil: int
        :param id_contenido: The id_contenido of this Visualizacion.  # noqa: E501
        :type id_contenido: int
        :param fecha_visualizacion: The fecha_visualizacion of this Visualizacion.  # noqa: E501
        :type fecha_visualizacion: date
        :param progreso: The progreso of this Visualizacion.  # noqa: E501
        :type progreso: int
        """
        self.openapi_types = {
            'id_perfil': int,
            'id_contenido': int,
            'fecha_visualizacion': date,
            'progreso': int
        }

        self.attribute_map = {
            'id_perfil': 'id_perfil',
            'id_contenido': 'id_contenido',
            'fecha_visualizacion': 'fecha_visualizacion',
            'progreso': 'progreso'
        }

        self._id_perfil = id_perfil
        self._id_contenido = id_contenido
        self._fecha_visualizacion = fecha_visualizacion
        self._progreso = progreso

    @classmethod
    def from_dict(cls, dikt) -> 'Visualizacion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Visualizacion of this Visualizacion.  # noqa: E501
        :rtype: Visualizacion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_perfil(self) -> int:
        """Gets the id_perfil of this Visualizacion.


        :return: The id_perfil of this Visualizacion.
        :rtype: int
        """
        return self._id_perfil

    @id_perfil.setter
    def id_perfil(self, id_perfil: int):
        """Sets the id_perfil of this Visualizacion.


        :param id_perfil: The id_perfil of this Visualizacion.
        :type id_perfil: int
        """

        self._id_perfil = id_perfil

    @property
    def id_contenido(self) -> int:
        """Gets the id_contenido of this Visualizacion.


        :return: The id_contenido of this Visualizacion.
        :rtype: int
        """
        return self._id_contenido

    @id_contenido.setter
    def id_contenido(self, id_contenido: int):
        """Sets the id_contenido of this Visualizacion.


        :param id_contenido: The id_contenido of this Visualizacion.
        :type id_contenido: int
        """

        self._id_contenido = id_contenido

    @property
    def fecha_visualizacion(self) -> date:
        """Gets the fecha_visualizacion of this Visualizacion.


        :return: The fecha_visualizacion of this Visualizacion.
        :rtype: date
        """
        return self._fecha_visualizacion

    @fecha_visualizacion.setter
    def fecha_visualizacion(self, fecha_visualizacion: date):
        """Sets the fecha_visualizacion of this Visualizacion.


        :param fecha_visualizacion: The fecha_visualizacion of this Visualizacion.
        :type fecha_visualizacion: date
        """

        self._fecha_visualizacion = fecha_visualizacion

    @property
    def progreso(self) -> int:
        """Gets the progreso of this Visualizacion.

        El porcentaje visualizado de un capítulo. Mínimo 0, máximo 100  # noqa: E501

        :return: The progreso of this Visualizacion.
        :rtype: int
        """
        return self._progreso

    @progreso.setter
    def progreso(self, progreso: int):
        """Sets the progreso of this Visualizacion.

        El porcentaje visualizado de un capítulo. Mínimo 0, máximo 100  # noqa: E501

        :param progreso: The progreso of this Visualizacion.
        :type progreso: int
        """

        self._progreso = progreso
