from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ActualizarDispositivosRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, dispositivo_id=None):  # noqa: E501
        """ActualizarDispositivosRequest - a model defined in OpenAPI

        :param dispositivo_id: The dispositivo_id of this ActualizarDispositivosRequest.  # noqa: E501
        :type dispositivo_id: int
        """
        self.openapi_types = {
            'dispositivo_id': int
        }

        self.attribute_map = {
            'dispositivo_id': 'dispositivoId'
        }

        self._dispositivo_id = dispositivo_id

    @classmethod
    def from_dict(cls, dikt) -> 'ActualizarDispositivosRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The actualizarDispositivos_request of this ActualizarDispositivosRequest.  # noqa: E501
        :rtype: ActualizarDispositivosRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dispositivo_id(self) -> int:
        """Gets the dispositivo_id of this ActualizarDispositivosRequest.


        :return: The dispositivo_id of this ActualizarDispositivosRequest.
        :rtype: int
        """
        return self._dispositivo_id

    @dispositivo_id.setter
    def dispositivo_id(self, dispositivo_id: int):
        """Sets the dispositivo_id of this ActualizarDispositivosRequest.


        :param dispositivo_id: The dispositivo_id of this ActualizarDispositivosRequest.
        :type dispositivo_id: int
        """

        self._dispositivo_id = dispositivo_id
