from datetime import date, datetime  # noqa: F401

from typing import List, Dict

from openapi_server import util
from openapi_server import db

class DispositivosUsuarioDB(db.Model):
    """
      NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
    	Do not edit the class manually.
    """

    __tablename__ = 'dispositivos_usuario'

    # Primary key composed by two columns
    dispositivo_id = db.Column(db.Integer, nullable=False, primary_key=True)
    user_id = db.Column(db.Integer, nullable=False, primary_key=True)

    def __init__(self, dispositivo_id, user_id):  # noqa: E501
        """DispositivosUsuarioDB - a model defined 

        :param dispositivo_id: The dispositivo_id of this .  # noqa: E501
        :type dispositivo_id: int
        :param user_id: The user_id of this .  # noqa: E501
        :type user_id: int
        """
        self.openapi_types = {
            'dispositivo_id': int,
            'user_id': int,
        }

        self.attribute_map = {
            'dispositivo_id': 'dispositivo_id',
            'user_id': 'user_id',
        }

        self.dispositivo_id = dispositivo_id
        self.user_id = user_id 
    
    def serialize(self):
        return {
            'dispositivo_id': self.dispositivo_id,
            'user_id': self.user_id,
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DispositivosUsuarioDB':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DispositivosUsuariosDB of this DispositivosUsuarioDB.  # noqa: E501
        :rtype: DispositivosUsuarioDB 
        """
        return util.deserialize_model(dikt, cls)
